spring:
  application:
    name: operacion-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: 8083

resilience4j:
  circuitbreaker:
    instances:
      cuentaService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      cuentaService:
        max-attempts: 3
        wait-duration: 1s
