CREATE TABLE NovaBank;

CREATE TABLE CLIENTES ( ID SERIAL PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL,
APELLIDOS VARCHAR(150) NOT NULL, DNI VARCHAR(20) UNIQUE NOT NULL,
EMAIL VARCHAR(150) UNIQUE NOT NULL, TELEFONO VARCHAR(20) UNIQUE NOT NULL,
 FECHA_CREACION NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE CUENTAS (ID SERIAL PRIMARY KEY, NUMERO_CUENTA VARCHAR(34) UNIQUE NOT NULL,
CLIENTE_ID INT NOT NULL, SALDO NUMERIC(15,2) DEFAULT 0 CHECK (SALDO >=0), FECHA_CREACION NOT NULL DEFAULT CURRENT_TIMESTAMP
FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID));

CREATE TABLE MOVIMIENTOS (ID SERIAL PRIMARY KEY, CUENTA_ID INT NOT NULL, TIPO VARCHAR(50)
CHECK(TIPO IN('DEPOSITO','RETIRO','TRANSFERENCIA_SALIENTE','TRANSFERENCIA_ENTRANTE')),
CANTIDAD NUMERIC(15,2), FECHA NOT NULL DEFAULT CURRENT_TIMESTAMP)