CREATE DATABASE NovaBank;
\c NovaBank

CREATE TABLE CLIENTES (ID SERIAL PRIMARY KEY,NOMBRE VARCHAR(100) NOT NULL,APELLIDOS VARCHAR(150) NOT NULL,
DNI VARCHAR(20) UNIQUE NOT NULL,EMAIL VARCHAR(150) UNIQUE NOT NULL,TELEFONO VARCHAR(20) UNIQUE NOT NULL,
FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE CUENTAS (ID SERIAL PRIMARY KEY,NUMERO_CUENTA VARCHAR(34) UNIQUE NOT NULL,CLIENTE_ID INT NOT NULL,
SALDO NUMERIC(15,2) DEFAULT 0 CHECK (SALDO >= 0),FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID) ON DELETE CASCADE);

CREATE TABLE MOVIMIENTOS (ID SERIAL PRIMARY KEY,CUENTA_ID INT NOT NULL,TIPO VARCHAR(50) NOT NULL
CHECK (TIPO IN ('DEPOSITO','RETIRO','TRANSFERENCIA_SALIENTE','TRANSFERENCIA_ENTRANTE')),
CANTIDAD NUMERIC(15,2) NOT NULL CHECK (CANTIDAD > 0),FECHA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (CUENTA_ID) REFERENCES CUENTAS(ID) ON DELETE CASCADE);