apiVersion: v1
kind: Secret
metadata:
  name: novabank-secrets-example
type: Opaque
data:
  # Ejemplo no productivo. Reemplazar por secretos reales gestionados fuera de Git.
  POSTGRES_USERNAME: bm92YWJhbms=
  POSTGRES_PASSWORD: bm92YWJhbms=
  JWT_SECRET: UkVQTEFDRV9NRV9CQVNFNjQ=
  AWS_ACCESS_KEY_ID: dGVzdA==
  AWS_SECRET_ACCESS_KEY: dGVzdA==
